{{- if .Values.config.jetstream.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "surveyor.fullname" . }}-accounts
  labels:
    {{- include "surveyor.labels" . | nindent 4 }}
data:
  {{- range .Values.config.jetstream.accounts }}
  {{ .name }}.json: |
    {{ . | toJson }}
  {{- end }}
{{- end }}
